services:

  postgres:
    logging:
      driver: local
    image: postgres:12
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=te_canvas
      - POSTGRES_USER=te_canvas_user
      - POSTGRES_PASSWORD

  postgres-test:
    logging:
      driver: local
    profiles: [ test ]
    image: postgres:12
    volumes:
      - type: volume
        source: postgres-data-test
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports: [ 127.0.0.1:5433:5432 ]

  api:
    logging:
      driver: local
    image: docker.sunet.se/te-canvas-api:${TAG_API-latest}
    depends_on: [ postgres ]
    environment:
      - TE_ID
      - TE_USERGROUP
      - TE_GENERAL_ID_FIELD=${TE_GENERAL_ID_FIELD-general.title}
      - TE_GENERAL_TITLE_FIELD=${TE_GENERAL_TITLE_FIELD-general.id}

      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=te_canvas
      - POSTGRES_USER=te_canvas_user
      - POSTGRES_PASSWORD
    networks: [ te-canvas, default ]

  sync:
    logging:
      driver: local
    image: docker.sunet.se/te-canvas-sync:${TAG_SYNC-latest}
    depends_on: [ postgres ]
    environment:
      - TE_ID
      - TE_USERGROUP

      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD
      - TE_GENERAL_ID_FIELD=${TE_GENERAL_ID_FIELD-general.title}
      - TE_GENERAL_TITLE_FIELD=${TE_GENERAL_TITLE_FIELD-general.id}

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=te_canvas
      - POSTGRES_USER=te_canvas_user
      - POSTGRES_PASSWORD

      - MAX_WORKERS=1

volumes:
  postgres-data:
  postgres-data-test:

networks:
  te-canvas:
    external: true
