version: '3.7'
services:
  postgres:
    image: "postgres:12"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
  postgres-test:
    image: "postgres:12"
    volumes:
      - type: volume
        source: postgres-data-test
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    ports:
      - 5433:5432

volumes:
  postgres-data:
  postgres-data-test:
