services:

  postgres:
    profiles: [ sync, api ]
    image: postgres:12
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks: [ te-canvas ]

  postgres-test:
    profiles: [ test ]
    image: postgres:12
    volumes:
      - type: volume
        source: postgres-data-test
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    networks: [ te-canvas ]

  api:
    profiles: [ api ]
    build:
      context: .
      dockerfile: Dockerfile_api
    depends_on: [ postgres ]
    environment:
      - TE_WSDL_URL
      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks: [ te-canvas ]

  sync:
    profiles: [ sync ]
    build:
      context: .
      dockerfile: Dockerfile_sync
    depends_on: [ postgres ]
    environment:
      - TE_WSDL_URL
      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

      - EVENT_TITLE
      - EVENT_LOCATION
      - EVENT_DESCRIPTION
    networks: [ te-canvas ]

volumes:
  postgres-data:
  postgres-data-test:
networks:
  te-canvas:
    external: true
