services:

  postgres:
    logging:
      driver: local
    profiles: [ sync, api ]
    image: postgres:12
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=te_canvas
      - POSTGRES_USER=te_canvas_user
      - POSTGRES_PASSWORD

  postgres-test:
    logging:
      driver: local
    profiles: [ test ]
    image: postgres:12
    volumes:
      - type: volume
        source: postgres-data-test
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password

  api:
    logging:
      driver: local
    profiles: [ api ]
    image: docker.sunet.se/te-canvas-api
    depends_on: [ postgres ]
    environment:
      - TE_WSDL_URL
      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=te_canvas
      - POSTGRES_USER=te_canvas_user
      - POSTGRES_PASSWORD
    networks: [ te-canvas ]

  sync:
    logging:
      driver: local
    profiles: [ sync ]
    image: docker.sunet.se/te-canvas-sync
    depends_on: [ postgres ]
    environment:
      - TE_WSDL_URL
      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=te_canvas
      - POSTGRES_USER=te_canvas_user
      - POSTGRES_PASSWORD

      - EVENT_TITLE
      - EVENT_LOCATION
      - EVENT_DESCRIPTION

volumes:
  postgres-data:
  postgres-data-test:

networks:
  te-canvas:
    external: true
