FROM python:3

WORKDIR /usr/src/app

COPY requirements/prod.txt .
RUN pip install --no-cache-dir -r prod.txt

COPY te_canvas te_canvas

ENV PYTHONPATH=/usr/src/app

CMD [ "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "te_canvas.api:create_app()" ]
