version: '3.7'
services:

  postgres:
    profiles: ["sync", "api"]
    image: "postgres:12"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:5432

  postgres-test:
    profiles: ["testing"]
    image: "postgres:12"
    volumes:
      - type: volume
        source: postgres-data-test
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    ports:
      - 5433:5432

  api-server:
    profiles: ["api"]
    build:
      context: .
      dockerfile: Dockerfile_api
    depends_on: [ postgres ]
    ports: [ 127.0.0.1:5000:5000 ]
    environment:
      - TE_WSDL_URL
      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  syncer:
    profiles: ["sync"]
    build:
      context: .
      dockerfile: Dockerfile_sync
    depends_on: [ postgres ]
    environment:
      - TE_WSDL_URL
      - TE_CERT
      - TE_USERNAME
      - TE_PASSWORD

      - CANVAS_URL
      - CANVAS_KEY

      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

      - EVENT_TITLE
      - EVENT_LOCATION
      - EVENT_DESCRIPTION

volumes:
  postgres-data:
  postgres-data-test:
