# NOTE: Not for production
services:
  postgres:
    ports: [ 127.0.0.1:5432:5432 ]
  api:
    ports: [ 127.0.0.1:5000:5000 ]
    build:
      context: .
      dockerfile: Dockerfile_api
  sync:
    build:
      context: .
      dockerfile: Dockerfile_sync
