FROM python:3

WORKDIR /usr/src/app

COPY requirements/prod.txt .
RUN pip install --no-cache-dir -r prod.txt

COPY te_canvas te_canvas

ENV PYTHONPATH=/usr/src/app

CMD [ "python", "-m", "te_canvas.sync" ]
