version: '3.7'
services:
  postgres:
    image: "postgres:12"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432

volumes:
  postgres-data:
    external: false
